### ISSUE TITLE
Raw 16-bit load-store was used

### ISSUE THREAD

**Issue by udev** [HansKristian-Work/dxil-spirv#28] opened 2020-12-12 07:35 UTC
I'm encountering the following error while attempting to run Cyberpunk 2077 with Proton 5.13-4:

> Dec 12 01:19:00 steam steam.desktop[17194]: 216:err:vkd3d_dxil_log_callback: dxil-spirv: Raw 16-bit load-store was used, which must be implemented with SSBO or BDA.
> Dec 12 01:19:00 steam steam.desktop[17194]: 216:err:vkd3d_dxil_log_callback: dxil-spirv: Failed to convert function.

More details here: https://github.com/ValveSoftware/Proton/issues/4450#issuecomment-743422061

Since adding the above comment on the ValveSoftware/Proton issue tracker I have updated to the latest Mesa git:

> steam@steam:~$ glxinfo | grep OpenGL
> OpenGL vendor string: AMD
> OpenGL renderer string: AMD Radeon R9 200 Series (HAWAII, DRM 3.39.0, 5.9.0-4-amd64, LLVM 11.0.0)
> OpenGL core profile version string: 4.6 (Core Profile) Mesa 21.0.0-devel (git-d7911f9c6b)
> OpenGL core profile shading language version string: 4.60
> OpenGL core profile context flags: (none)
> OpenGL core profile profile mask: core profile
> OpenGL core profile extensions:
> OpenGL version string: 4.6 (Compatibility Profile) Mesa 21.0.0-devel (git-d7911f9c6b)
> OpenGL shading language version string: 4.60
> OpenGL context flags: (none)
> OpenGL profile mask: compatibility profile
> OpenGL extensions:
> OpenGL ES profile version string: OpenGL ES 3.2 Mesa 21.0.0-devel (git-d7911f9c6b)
> OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
> OpenGL ES profile extensions:

**Comment by fabianhjr** [comment] 2020-12-19 08:01
Can reproduce on NixOS with Steam/Proton faltpak if it helps:

```
>>> Adding process 9653 for game ID 1091500
Game update: AppID 1091500 "", ProcID 9642, IP 0.0.0.0:0
RecordSteamInterfaceCreation (PID 9642): SteamUtils010 / 
Setting breakpad minidump AppID = 1091500
RecordSteamInterfaceCreation (PID 9642): SteamUser021 / User
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198035510815 [API loaded no]
RecordSteamInterfaceCreation (PID 9642): SteamUser021 / 
RecordSteamInterfaceCreation (PID 9642): STEAMUSERSTATS_INTERFACE_VERSION012 / 
Fossilize INFO: Overriding serialization path: "/home/fabian/.local/share/Steam/steamapps/shadercache/1091500/fozpipelinesv4/steamapprun_pipeline_cache".
Fossilize INFO: Overriding serialization path: "/home/fabian/.local/share/Steam/steamapps/shadercache/1091500/fozpipelinesv4/steamapprun_pipeline_cache".
RecordSteamInterfaceCreation (PID 9642): STEAMAPPS_INTERFACE_VERSION008 / 
272:err:vkd3d_dxil_log_callback: dxil-spirv: Raw 16-bit load-store was used, which must be implemented with SSBO or BDA.
272:err:vkd3d_dxil_log_callback: dxil-spirv: Failed to convert function.
RecordSteamInterfaceCreation (PID 9642): SteamUtils010 / 
RecordSteamInterfaceCreation (PID 9642): SteamController007 / 
RecordSteamInterfaceCreation (PID 9642): SteamInput001 / 
RecordSteamInterfaceCreation (PID 9642): SteamFriends017 / 
```

And system info (nvidia)

```
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 1070/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 455.45.01
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6.0 NVIDIA 455.45.01
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 455.45.01
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

**Comment by zogxray** [comment] 2020-12-25 23:45
Same on proton-experimental

```
280:err:vkd3d_dxil_log_callback: dxil-spirv: Raw 16-bit load-store was used, which must be implemented with SSBO or BDA.
280:err:vkd3d_dxil_log_callback: dxil-spirv: Failed to convert function.
```

**Comment by HansKristian-Work** [comment] 2021-01-20 14:08
Not a bug (old workaround for CP77 forced this to trigger), and fixed in vkd3d-proton already.

**Closed by HansKristian-Work** 2021-01-20 14:08 UTC
